# Generated by Django 4.0.2 on 2022-03-11 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('course_num', models.CharField(max_length=20)),
                ('num_credits', models.FloatField(default=-1)),
                ('department', models.CharField(default='', max_length=255, null=True)),
                ('level', models.CharField(default='', max_length=500, null=True)),
                ('prerequisites', models.TextField(default='', null=True)),
                ('corequisites', models.TextField(default='', null=True)),
                ('school', models.CharField(db_index=True, max_length=100)),
                ('campus', models.CharField(default='', max_length=300)),
                ('notes', models.TextField(default='', null=True)),
                ('info', models.TextField(default='', null=True)),
                ('exclusions', models.TextField(default='')),
                ('instructors', models.CharField(default='TBA', max_length=500)),
                ('is_writing_intensive', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_section_id', models.IntegerField(default=0)),
                ('meeting_section', models.CharField(max_length=50)),
                ('size', models.IntegerField(default=-1)),
                ('enrollment', models.IntegerField(default=-1)),
                ('waitlist', models.IntegerField(default=-1)),
                ('waitlist_size', models.IntegerField(default=-1)),
                ('section_type', models.CharField(default='L', max_length=50)),
                ('instructors', models.CharField(default='TBD', max_length=500)),
                ('was_full', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', max_length=350)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
