# Generated by Django 4.0.2 on 2022-04-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='waitlist',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
