# Generated by Django 4.0.2 on 2022-04-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_enrollment_remove_course_waitlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_credits',
            field=models.CharField(max_length=15),
        ),
    ]
