# Generated by Django 4.0.2 on 2022-04-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_num_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.TextField(default='', null=True),
        ),
    ]
