version: '3'

services:
    db:
        image: postgres:14
        env_file:
            - jhcourserevu/.env
        # environment:
            # - POSTGRES_USER=postgres
            # - POSTGRES_PASSWORD=""
            # - POSTGRES_DB=postgres
            # - POSTGRES_DB_HOST=postgres
            # - POSTGRES_USER=${DB_USER}
            # - POSTGRES_PASSWORD=${DB_PASSWORD}
            # - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8080:8080"
        depends_on:
            - db

volumes:
  postgres_data: