version: '3.10'

services:
  db:
    image: postgres:14
    ports:
        - "5432:5432"

  web:
    build: .
    command: [sh, -c, "pip install -q -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    restart: on-failure
    depends_on:
        - db
