version: '3.10'

services:
  db:
    image: postgres:14
    env_file:
        - jhcourserevu/.env
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=""
    ports:
        - "5432:5432"

  web:
    build: .
    command: [sh, -c, "pip install -q -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    depends_on:
        - db
