# Generated by Django 4.0.2 on 2022-03-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
