# Generated by Django 4.0.2 on 2022-04-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0014_alter_customuser_is_admin'),
        ('user', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.customuser'),
        ),
    ]
