name: Deploy the Backend

on:
  pull_request:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6

  push:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6

    paths:
      - "code/backend/**"
      - ".github/workflows/backend.yml"

defaults:
  run:
    working-directory: code/backend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # TODO: add back once working locally
      # - name: Run Tests
      #   run: |
      #     python manage.py test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jhcourserevu-api-test" #Must be unique in Heroku
          heroku_email: "jhcourserevu@gmail.com"
          appdir: "code/backend"
          # env:
          #   SECRET_KEY: ${{secrets.SECRET_KEY}}
          procfile: "web: python manage.py runserver 0.0.0.0:$PORT"

