name: Deploy Frontend - Production

on:
  push:
    branches:
      - main

    paths:
      - "code/frontend/**"
      - ".github/workflows/frontend.yml"

  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: code/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: npm install and build webpack
        run: |
          npm ci
          npm install
          npm run build --if-present

      - name: Deploy Site
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./code/frontend/dist"
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          netlify-config-path: ""./code/netlify.toml"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_DJANGO_CLIENT_ID: ${{ secrets.VITE_DJANGO_CLIENT_ID }}
          VITE_DJANGO_CLIENT_SECRET: ${{ secrets.VITE_DJANGO_CLIENT_ID }}
        timeout-minutes: 1
