name: Deploy the frontend

on:
  pull_request:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6
      # TODO: remove these below later
      - frontend/initialize
  
  push:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6
      # TODO: remove these below later
      - frontend/initialize
    paths:
      - "code/frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install and build webpack
        run: |
          npm install
          npm run build --if-present
  
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and test
      run: |
        npm install
        npm install -g eslint
        npm install -g prettier
        npx prettier "**/*.{js,jsx,ts,tsx}" --check 
        eslint . --ext .js,.jsx,.ts,.tsx --max-warnings 0
      env:
        CI: true
    # - name: Run Prettier
    #     run: npx prettier "**/*.{js,jsx,ts,tsx}" --check 
    # - name: Run ESLint
    #   run: eslint . --ext .js,.jsx,.ts,.tsx --max-warnings 0
