name: Frontend Test & Lint

on:
  push:
    branches:
      - main

    paths:
      - "code/frontend/**"
      - ".github/workflows/frontend.yml"

defaults:
  run:
    working-directory: code/frontend

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: code/frontend/package-lock.json
      - name: npm install and build webpack
        run: |
          npm ci
          npm install
          npm run build --if-present
      
      - name: npm install linters
        run: |
          npm install -g eslint
          npm install -g prettier
        env:
          CI: true
      - name: Run Prettier
        run: npx prettier "**/*.{js,jsx,ts,tsx}" --check 
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx --max-warnings 0

# TODO: add Jest, Vitest, or etc.
# npm test