name: DEPLOY THE FRONTEND

on:
  pull_request:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6
  
  push:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6

    paths:
      - "code/frontend/**"
      - ".github/workflows/frontend.yml"

defaults:
  run:
    working-directory: code/frontend

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: code/frontend/package-lock.json
      - name: npm install and build webpack
        run: |
          npm ci
          npm install
          npm run build --if-present

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=public --prod

# TODO: add Jest, Vitest, or etc.
# npm test
