name: Deploy the frontend

on:
  pull_request:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6
      # TODO: remove these below later
      - frontend/initialize
  
  push:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6
      # TODO: remove these below later
      - frontend/initialize
    paths:
      - "code/frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      with:
      #   node-version: 14
      #   cache: "npm"
      # - name: Install Dependencies
      #   run: cd code/frontend
      #   run: npm install
      # - name: Run Test Suite
      #   - run: npm -g install chromedriver
      #   - run: npm -g install jest@20
      #   - run: npm run build --if-present
      #   - run: npm run lint
      #   - run: npm run test
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm -g install chromedriver
      - run: npm -g install jest@20
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run test
