name: Deploy Frontend - Staging

on:
  pull_request:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6

  push:
    branches:
      - main
      - iteration-1
      - iteration-2
      - iteration-3
      - iteration-4
      - iteration-5
      - iteration-6

    paths:
      - "code/frontend/**"
      - ".github/workflows/frontend.yml"

defaults:
  run:
    working-directory: code/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"
      #     cache-dependency-path: code/frontend/package-lock.json
      - name: npm install and build webpack
        run: |
          npm ci
          npm install
          npm run build --if-present

      - name: Deploy Site
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './code/frontend/dist'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STAGE_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        timeout-minutes: 1
