name: Deploy Frontend

on:
  push:
    branches:
      - main

    paths:
      - "code/frontend/**"
      - ".github/workflows/frontend.yml"

defaults:
  run:
    working-directory: code/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: code/frontend/package-lock.json
      - name: npm install and build webpack
        run: |
          npm ci
          npm install
          npm run build --if-present

      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=public --prod
